# Use this file to templatize your application's native configuration files.
# See the docs at https://www.habitat.sh/docs/create-packages-configure/.
# You can safely delete this file if you don't need it.

worker_processes = 4

[events]
worker_connections = 4

[http]
sendfile = "on"
tcp_nopush = "on"
tcp_nodelay = "on"
keepalive_timeout = 15
[http.listen]
port = 80

